version: "3.6"

volumes:
  dataset-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LOCAL_DATASET_PATH-./data}
  models-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LOCAL_MODELS_PATH-./models}
  notebooks-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./notebooks
services:
  jupyterlab:
    image: andreper/jupyterlab:3.0.0-spark-3.0.0
    container_name: jupyterlab
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - notebooks-volume:/opt/workspace
      - dataset-volume:/opt/workspace/dataset
      - models-volume:/home/jovyan/models
  spark-master:
    image: andreper/spark-master:3.0.0
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    volumes:
      - notebooks-volume:/opt/workspace
      - dataset-volume:/opt/workspace/dataset
      - models-volume:/home/jovyan/models
    ports:
      - 8080:8080
      - 7077:7077
  spark-worker-1:
    image: andreper/spark-worker:3.0.0
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    depends_on:
      - spark-master
    volumes:
      - notebooks-volume:/opt/workspace
      - dataset-volume:/opt/workspace/dataset
      - models-volume:/home/jovyan/models
  spark-worker-2:
    image: andreper/spark-worker:3.0.0
    container_name: spark-worker-2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    depends_on:
      - spark-master
    volumes:
      - notebooks-volume:/opt/workspace
      - dataset-volume:/opt/workspace/dataset
      - models-volume:/home/jovyan/models
