# https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker
version: "3.6"

volumes:
  dataset-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LOCAL_DATASET_PATH-./data}
  models-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LOCAL_MODELS_PATH-./models}
  notebooks-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./notebooks
  elasticsearch-data-single:
    driver: local
services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyterlab
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - notebooks-volume:/opt/workspace
      - dataset-volume:/opt/workspace/dataset
      - models-volume:/opt/workspace/models
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    volumes:
      - notebooks-volume:/opt/workspace
      - dataset-volume:/opt/workspace/dataset
      - models-volume:/opt/workspace/models
    ports:
      - 8080:8080
      - 7077:7077
  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2048m
    ports:
      - 8081:8081
    depends_on:
      - spark-master
    volumes:
      - notebooks-volume:/opt/workspace
      - dataset-volume:/opt/workspace/dataset
      - models-volume:/opt/workspace/models
  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-worker-2
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2048m
    ports:
      - 8082:8081
    depends_on:
      - spark-master
    volumes:
      - notebooks-volume:/opt/workspace
      - dataset-volume:/opt/workspace/dataset
      - models-volume:/opt/workspace/models
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    volumes:
      - elasticsearch-data-single:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    ports:
      - 5601:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
